service: my-service
frameworkVersion: ^3.22.0

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
          Resource:
            - !GetAtt MyQueue.Arn
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - !Ref MySNSTopic

package:
  patterns:
    - '!package.json'
    - '!package-lock.json'

functions:
  sendMessage:
    handler: producer.handler
    events:
      - http:
          path: /send-message
          method: post
    environment:
      SQS_QUEUE_URL: !Ref MyQueue
  processMessage:
    handler: consumer.handler
    events:
      - sqs:
          arn: !GetAtt MyQueue.Arn
          batchSize: 1
    environment:
      SNS_TOPIC_ARN: !Ref MySNSTopic

resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "my-queue"
    MySNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "My SNS Topic"
        TopicName: "my-sns-topic"
    MyEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn: !Ref MySNSTopic
        Endpoint: mail@example.com
